AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - pdfserve_client.gemspec

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/OpenStructUse:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - lib/pdfserve/client.rb
    - lib/pdfserve/merge.rb
    - lib/pdfserve/split.rb
    - lib/pdfserve/stamp.rb

Metrics/AbcSize:
  Exclude:
    - lib/pdfserve/client.rb
    - lib/pdfserve/merge.rb
    - lib/pdfserve/split.rb
    - lib/pdfserve/stamp.rb
